name: Continuous Integration
on: push


jobs:
  clang-format:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: clang-format-12 -i $(find . -iname '*.cpp' -or -iname '*.c' -or -iname '*.h' -and -not -iname 'doctest.h')
      - run: |
          git add .
          git commit -m "Automatic code format done by clang-format" || echo "Nothing to commit"
          git push || echo "Nothing to push"
  cppcheck:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: cppcheck --version
      - run: cppcheck -Iinclude --language=c++ -DSOME_DEFINE_TO_FIX_CONFIG --enable=all --suppress=*:doctest.h --error-exitcode=1 --inline-suppr $(find . -iname '*.cpp')
  server-build:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake .. -D=BUILD_ALL=OFF -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON
      - run: |
          cd build
          make server
