name: Continuous Integration
on: push


jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      client: ${{ steps.filter.outputs.client }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            server:
              - 'server/**'
            client:
              - 'client/**'
  clang-format:
    runs-on: ubuntu-latest
    container: ghcr.io/khbminus/fasttyping-ci:base
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: clang-format-12 -i $(find . -iname '*.cpp' -or -iname '*.c' -or -iname '*.h' -and -not -iname 'doctest.h')
      - run: |
          git config --global user.email "github-runner@nowhere.kek"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Automatic code format done by clang-format" || echo "Nothing to commit"
          git push || echo "Nothing to push"
  cppcheck-client:
    needs: [ clang-format, changes ]
    if: ${{ needs.changes.outputs.client == 'true' }}
    runs-on: ubuntu-latest
    container: ghcr.io/khbminus/fasttyping-ci:base
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: cppcheck --version
      - run: cd client && cppcheck --suppressions-list=supressions-list.txt -Iinclude --language=c++ -DSOME_DEFINE_TO_FIX_CONFIG --enable=all --suppress=*:doctest.h --suppress=unmatchedSuppression --error-exitcode=1 --inline-suppr $(find . -iname '*.cpp' ! -iname '*tests*.cpp')
  cppcheck-server:
    needs: [ clang-format, changes ]
    if: ${{ needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    container: ghcr.io/khbminus/fasttyping-ci:base
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: cppcheck --version
      - run: cd server && cppcheck --suppressions-list=supressions-list.txt -Iinclude --language=c++ -DSOME_DEFINE_TO_FIX_CONFIG --enable=all --suppress=*:doctest.h --suppress=unmatchedSuppression --error-exitcode=1 --inline-suppr $(find . -iname '*.cpp' ! -iname '*tests*.cpp')

  server-build:
    needs: [ cppcheck-server, changes ]
    if: ${{ needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    container: ghcr.io/khbminus/fasttyping-ci:base
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake .. -DBUILD_ALL=OFF -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON
      - run: |
          cd build
          make server
  client-build:
    needs: [ cppcheck-client, changes ]
    if: ${{ needs.changes.outputs.client == 'true' }}
    runs-on: ubuntu-latest
    container: ghcr.io/khbminus/fasttyping-ci:client
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir build
          cd build
          cmake .. -DBUILD_ALL=OFF -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF
      - run: |
          cd build
          make client
  deploy:
    needs: [ server-build ]
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
