name: Continuous Integration
on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'server/**'

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    environment: server-env
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd fastTyping
            git pull
            git switch master
            sudo systemctl stop ftServer.service
            mkdir build
            cd build
            cmake .. -DBUILD_ALL=OFF -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON
            make server
            make dictionaries-interface
            echo "built"
            sudo FASTTYPING_DB=fast_typing ./server/dictionaries-interface 
            cp server/server ../../server
            cd ..
            rm -rf build
            sudo systemctl start ftServer.service
            echo "started"
      - uses: actions/checkout@v2
      - run: chmod +x .github/scripts/health_check.py && .github/scripts/health_check.py
